lab6/urls.py
from .views import *
from django.shortcuts import render
from django.urls import path

app_name = 'lab6'
urlpatterns = [
    path('', status, name='status'),
    path('save_status/', save_status, name='save_status'),
]

lab7/urls.py
from .views import *
from django.shortcuts import render
from django.urls import path

app_name = 'lab7'
urlpatterns = [
    path('', lab7View, name='lab7'),
]

story6/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lab6.urls')),
    path('story7', include('lab7.urls'))
]

lab6/models.py
from django.db import models
import datetime

# Create your models here.
class Status(models.Model):
	date = models.DateTimeField(auto_now_add=True)
	status = models.TextField(max_length=300)

lab7/models.py
from django.db import models

# Create your models here.

lab8/models.py
from django.db import models

# Create your models here.

lab6/forms.py
from django import forms
from .models import Status
from django.forms import ModelForm

class StatusForm(ModelForm):
    class Meta:
        model = Status
        fields = ['status']
        labels = {'status': 'Status'}
        widgets = {
            'status': forms.Textarea(attrs={
            'class': 'form-control','type' : 'textarea', 'rows' : '4', 'id':'status'}),
        }

lab6/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import StatusForm
from .models import Status

# Create your views here.
def status(request):
	status = Status.objects.order_by('date')
	form = StatusForm(request.POST)
	content = {'form' : form, 'status': status}
	return render(request, 'steven.html', content)

def save_status(request):
	if request.method == 'POST':
		form = StatusForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('lab6:status')
	else:
		return redirect('lab6:status')

lab7/views.py
from django.shortcuts import render

# Create your views here.
def lab7View(request):
    return render(request,'lab7.html')

lab8/views.py
from django.shortcuts import render

# Create your views here.

lab6/templates/steven.html
{% load static %}
<!DOCTYPE html>
<html>
    <link rel="stylesheet"  href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet"  href="{% static 'css/styles.css' %}">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
    <head>
        <title>steven</title>
    </head>

    <body class="form-body">

        <div class="form-cont">
            <h2>Halo, apa kabar?</h2>
            <form method="POST" action="{% url 'lab6:save_status' %}" class="form">
                {% csrf_token %}
                <p>Status</p>
                {{ form.status }}
                <div class="full">
                    <input type="Submit" class="btn btn-primary" value="Submit" id="submit" />
                </div>
            </form>
        </div>

        <div class="list-group" style="padding: 40px 100px 30px 100px">
            <p style="color: red; font-family:'Varela Round', sans-serif; font-size: 30px" class="stats"><b><span style="color:blue; background-color: rgba(255,255,255,0.5)">Your</span> Status </b></p>
            {% for db in status %}
                <div style="background-color: #ffafaf; padding: 30px; word-wrap: break-word;" class='stats'>
                    <h4 class="mb-1"><b>{{ db.status }}</b></h4>
                    <small class="text-muted">{{ db.date }}</small>
                </div>
                <br>
            {% endfor %}
        </div>
        
    </body>
</html>

lab7/templates/lab7.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>jQuery UI Accordion - Default functionality</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet"  href="{% static 'css/styles.css' %}">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script src="{% static 'scripts.js' %}"></script>
</head>

<body>
  
 <h1>Hi! I'm Steven</h1>

<div id="accordion">
  <h3>Activities</h3>
  <div>
    <p>Basically my daily activities are:</p>
    <ul>
      <li>Eat</li>
      <li>Code</li>
      <li>Sleep</li>
      <li>Repeat</li>
    </ul>
  </div>
  <h3>Organization</h3>
  <div>
    <p>Aku apatis :(</p>
  </div>
  <h3>Achievement</h3>
  <div>
    <p><b>C O M I N G  S O O N</b></p>
  </div>
</div>

<br><br><br>
<button type="button" id="btn">Change Theme</button>
 
</body>
</html>

templates/base.html
{% load static from staticfiles%}


<!DOCTYPE html> 
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <title>{% block title %}{% endblock %}</title>
    
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" >
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" > 
    

    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/logo_tk1.ico' %}">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


  </head>
  <body>
    <!-- navbar -->
    <div class ="navbar-header">
    <nav class="navbar navbar-expand-sm navbar-inverse fixed-top" style="background-color: #fe5b46; font-family: 'Varela Round', sans-serif;">
      <a class="navbar-brand" href="/"><img src="{% static 'img/logo-tk1.png' %}" alt="logo" width="50px"></a>
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle-navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link" style="color: white;" href="/request">Request</a>
          <a class="nav-item nav-link" style="color: white" href="/contractor">Contractor</a>
          <a class="nav-item nav-link" style="color: white" href="/review">Review</a>
          <a class="nav-item nav-link" style="color: white" href="/">Contact Us</a>
        </div>
      </div>
    </nav>

    <!--content-->
    <div class="content-container">
      {% block content%} {% endblock %}
    </div>

      <!-- Footer -->
    <footer class="page-footer font-small pt-4">
      <div class="footer-copyright text-center py-3"><b>© Copyright PPW-KB12 2019</b></div>
    </footer>
  </body>
</html>

templates/index.html
{% load static from staticfiles%}


<!DOCTYPE html> 
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <title>Try
</title>

    
    <link href="{% static 'css/style.css' %}" rel="stylesheet"> 
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" >
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


  </head>
  <body>
    <h1>HELLO WORLD!</h1>
  </body>
</html>